Add interactive worktree selection using fzf

diff --git a/wt b/wt
--- a/wt
+++ b/wt
@@ -4,7 +4,7 @@ set -e
 # Switch between git worktrees with speed.
 
 args=("$@")
-VERSION="0.1.1"
+VERSION="0.1.2"
 TMP_PATH=$(mktemp)
 BINARY_PATH=$(which wt)
 JQ_URL="https://stedolan.github.io/jq/download"
@@ -14,6 +14,20 @@ RELEASE_API_URL="https://api.github.com/repos/yankeexe/git-worktree-switcher/rel
 
 # Escape forward slash
 arg=$(echo "${args[0]}" | sed 's/\//\\\//g')
+is_interactive=false
+
+for arg in "${args[@]}"; do
+    if [[ "$arg" == "-i" ]]; then
+		if command -v fzf &> /dev/null
+		then is_interactive=true
+		else
+			echo "Error: fzf is not installed for interactive mode"
+			echo "Install from: https://github.com/junegunn/fzf#installation"
+			exit 1
+		fi
+        break
+    fi
+done
 
 # show worktree list
 worktree_list() {
@@ -24,6 +38,7 @@ help_message() {
 	echo -e "wt lets you switch between your git worktrees with speed.\n"
 	echo "Usage:"
 	echo -e "\twt <worktree-name>: search for worktree names and change to that directory."
+	echo -e "\twt -i: interactively select a worktree using fzf."
 	echo -e "\twt list: list out all the git worktrees."
 	echo -e "\twt update: update to the latest release of worktree switcher."
 	echo -e "\twt version: show the CLI version."
@@ -99,7 +114,15 @@ version)
 	goto_main_worktree
 	;;
 *)
-	directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$arg"'/ {print; exit}' | cut -d ' ' -f2-)
+	if [[ "$is_interactive" == true ]]; then
+		directory=$(git worktree list --porcelain |
+		awk '/worktree/ {wt=$2} /branch/ {sub("refs/heads/", "", $2); print wt " [" $2 "]"}' |
+		fzf --query "" --height=10% --no-multi --exit-0 |
+		awk '{print $1}')
+	else
+		directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$arg"'/ {print; exit}' | cut -d ' ' -f2-)
+	fi
+
 	;;
 esac
 
